# Generated by Django 6.0.1 on 2026-01-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_remove_sport_icon_sport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('badminton', 'Badminton'), ('cricket', 'Cricket'), ('football', 'Football'), ('tennis', 'Tennis'), ('swimming', 'Swimming'), ('boxing', 'Boxing')], max_length=20, unique=True),
        ),
    ]
