# Generated by Django 6.0 on 2026-01-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_alter_sport_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(choices=[('peak', 'Peak Hours'), ('off_peak', 'Off-Peak Hours'), ('weekend', 'Weekend Premium'), ('holiday', 'Holiday Premium')], max_length=20)),
                ('start_time', models.TimeField(help_text='Start time for this pricing rule (e.g., 17:00)')),
                ('end_time', models.TimeField(help_text='End time for this pricing rule (e.g., 21:00)')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Price multiplier (e.g., 1.5 = 50% increase, 0.8 = 20% discount)', max_digits=3)),
                ('days_of_week', models.CharField(blank=True, help_text='Comma-separated day numbers (0=Sunday, 1=Monday, etc.) or leave blank for all days', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='venues.venue')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
