# Generated by Django 6.0 on 2026-01-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booking_reminders',
            field=models.BooleanField(default=True, help_text='Receive booking reminders'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='promotional_emails',
            field=models.BooleanField(default=False, help_text='Receive promotional emails'),
        ),
    ]
