# Generated by Django 6.0 on 2026-01-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_booking_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booking_reminders',
            field=models.BooleanField(default=True, help_text='Receive booking reminders'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='promotional_notifications',
            field=models.BooleanField(default=False, help_text='Receive promotional offers'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Receive push notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=True, help_text='Receive SMS notifications'),
        ),
    ]
