# Generated by Django 6.0 on 2026-01-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_booking_reminders_user_email_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='booking_reminders',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='promotional_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='push_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sms_notifications',
        ),
    ]
